"""add timestamp to rest

Revision ID: 36b94e3d76a4
Revises: c43b804e7f6c
Create Date: 2020-05-28 11:52:35.860185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36b94e3d76a4'
down_revision = 'c43b804e7f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_rest_timestamp'), 'rest', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rest_timestamp'), table_name='rest')
    op.drop_column('rest', 'timestamp')
    # ### end Alembic commands ###
