"""added rating and review count columns

Revision ID: 4eaec3964fab
Revises: 120f018224e8
Create Date: 2020-05-12 15:17:14.931327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eaec3964fab'
down_revision = '120f018224e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rest', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('rest', sa.Column('review_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rest', 'review_count')
    op.drop_column('rest', 'rating')
    # ### end Alembic commands ###
