"""added location col in posts

Revision ID: 932c23126f56
Revises: a48d9bbcefcb
Create Date: 2020-05-02 11:05:41.168449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932c23126f56'
down_revision = 'a48d9bbcefcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('location', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'location')
    # ### end Alembic commands ###
