"""added rest data column to Posts

Revision ID: a48d9bbcefcb
Revises: 197abaa4032f
Create Date: 2020-04-30 09:23:53.577326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48d9bbcefcb'
down_revision = '197abaa4032f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('rest_data', sa.String(length=700), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'rest_data')
    # ### end Alembic commands ###
